name: Go

on:
  push:
    branches: [ "main" ]

env:
  GOROOT: ''
  GOTOOLDIR: ''

jobs:

  build:
    runs-on: hyex
    steps:
    - uses: actions/checkout@v3

    - name: Check conditions
      run: echo $env:RUNNER_ENVIRONMENT
    
    - name: Check conditions
      run: echo $env:AGENT_ISSELFHOSTED
    
    - name: Check conditions
      run: echo $env:RUNNER_TOOL_CACHE
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
        cache: false

    - name: Check Before
      run: echo $env:GOROOT

    - name: Cleanup
      run: set $env:GOROOT=''

    - name: Check After
      run: echo $env:GOROOT
      
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
