name: Go

on:
  push:
    branches: [ "main" ]

env:
  GOROOT: ''
  AGENT_ISSELFHOSTED: 1

jobs:
  build:
    runs-on: hyex
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
        cache: false
      
    - name: Build
      run: go build -v ./...
